//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTrayApplication.Components.TrayIcon.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTrayApplication.Components.TrayIcon.Resources.Text.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDR.
        /// </summary>
        internal static string ProfileSummaryHdr {
            get {
                return ResourceManager.GetString("ProfileSummaryHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hz.
        /// </summary>
        internal static string ProfileSummaryHz {
            get {
                return ResourceManager.GetString("ProfileSummaryHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string ProfileSummaryPrimary {
            get {
                return ResourceManager.GetString("ProfileSummaryPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDR.
        /// </summary>
        internal static string ProfileSummarySdr {
            get {
                return ResourceManager.GetString("ProfileSummarySdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy display information to clipboard.
        /// </summary>
        internal static string TrayIconCopyDataToClipboard {
            get {
                return ResourceManager.GetString("TrayIconCopyDataToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close DeviceProfiles.
        /// </summary>
        internal static string TrayIconExitText {
            get {
                return ResourceManager.GetString("TrayIconExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles available.
        /// </summary>
        internal static string TrayIconNoProfilesAvailable {
            get {
                return ResourceManager.GetString("TrayIconNoProfilesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string TrayIconProfile {
            get {
                return ResourceManager.GetString("TrayIconProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Profile.
        /// </summary>
        internal static string TrayIconSwitchProfiles {
            get {
                return ResourceManager.GetString("TrayIconSwitchProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceProfiles.
        /// </summary>
        internal static string TrayIconTooltip {
            get {
                return ResourceManager.GetString("TrayIconTooltip", resourceCulture);
            }
        }
    }
}
