// <auto-generated />
using System;
using DeviceProfiles.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceProfiles.Infrastructure.Migrations
{
    [DbContext(typeof(DeviceProfilesDbContext))]
    [Migration("20230604145212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Domain.Entities.DeviceProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceProfiles");
                });

            modelBuilder.Entity("Domain.Entities.DeviceProfile", b =>
                {
                    b.OwnsMany("Domain.Entities.DisplaySettings", "DisplaySettings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("DeviceProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<uint>("DisplayId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("EnableHdr")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("PrimaryDisplay")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("RefreshRate")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceProfileId");

                            b1.ToTable("DisplaySettings");

                            b1.WithOwner()
                                .HasForeignKey("DeviceProfileId");
                        });

                    b.OwnsOne("Domain.ValueObjects.HotKeyCombination", "HotKey", b1 =>
                        {
                            b1.Property<int>("DeviceProfileId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Key")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Modifiers")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeviceProfileId");

                            b1.ToTable("DeviceProfiles");

                            b1.WithOwner()
                                .HasForeignKey("DeviceProfileId");
                        });

                    b.Navigation("DisplaySettings");

                    b.Navigation("HotKey");
                });
#pragma warning restore 612, 618
        }
    }
}
